use crate::wizard::state::WizardState;

pub fn generate(state: &WizardState) -> String {
    let scheme = crate::registry::colorschemes::COLORSCHEMES
        .get(state.colorscheme_index)
        .map(|s| s.name)
        .unwrap_or("catppuccin");

    format!(
        r#"-- =============================================================================
-- init.lua — configx generated Neovim configuration
--
-- Colorscheme : {scheme}
-- Explorer    : {explorer}
-- Keybindings : {keybindings}
--
-- Generated by configx <https://github.com/assemblyarc/configx>
-- =============================================================================

-- ── Bootstrap lazy.nvim ────────────────────────────────────────────────────
-- lazy.nvim is the plugin manager.  This block downloads it automatically
-- the first time Neovim is opened.
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({{
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  }})
end
vim.opt.rtp:prepend(lazypath)

-- ── Core configuration ─────────────────────────────────────────────────────
-- Load options, keymaps, and autocommands BEFORE plugins so that settings
-- like <leader> are available when plugin specs are evaluated.
require("config.options")
require("config.keymaps")
require("config.autocmds")

-- ── Plugins ────────────────────────────────────────────────────────────────
-- lazy.nvim will scan lua/plugins/ and load every file it finds.
-- Each file returns a table (or list of tables) of plugin specs.
require("lazy").setup({{
  spec = {{
    {{ import = "plugins" }},
  }},
  defaults = {{
    -- Plugins are lazy-loaded by default; each spec overrides this.
    lazy = true,
  }},
  install = {{
    -- Install missing plugins on startup.
    missing = true,
  }},
  checker = {{
    -- Automatically check for plugin updates once a day.
    enabled = true,
    frequency = 86400,
    notify = false,
  }},
  ui = {{
    border = "rounded",
  }},
}})
"#,
        scheme = scheme,
        explorer = state.explorer,
        keybindings = state.keybinding_style,
    )
}
